services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: javae
      POSTGRES_USER: javae
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d